spring:

  data:
    mongodb:
      uri: mongodb://localhost:27017/ems


  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: true


  main:
    allow-bean-definition-overriding: true


redis:
  host :localhost
port: 6379

